# Generated by Django 5.1.11 on 2025-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('registration_number', models.TextField(blank=True)),
                ('full_names', models.TextField(blank=True)),
                ('registration_date', models.DateField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('practice_type', models.TextField(blank=True)),
                ('license_type', models.TextField(blank=True)),
                ('license_no', models.CharField(blank=True, max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('postal_address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'managed': False,
            },
        ),
    ]
