# Generated by Django 5.1.11 on 2025-08-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('P', 'Premium')], default='B', help_text='Plan type: Basic, Standard, or Premium', max_length=1, unique=True),
        ),
    ]
