# Generated by Django 5.1.11 on 2025-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('site_name', models.CharField(default='My Website', max_length=255)),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='developerdocumentation',
            name='professional_endpoint',
            field=models.URLField(default='https://api.pkenya.co.ke', help_text='The endpoint for the professional api (paid)', unique=True),
        ),
        migrations.AlterField(
            model_name='developerdocumentation',
            name='url',
            field=models.URLField(default='https://docs.pkenya.co.ke', help_text='Mintlify Documentation', unique=True),
        ),
    ]
