# Generated by Django 5.1.11 on 2025-08-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('date_notified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maintenance Subscriber',
                'verbose_name_plural': 'Maintenance Subscribers',
                'ordering': ['-date_joined'],
            },
        ),
    ]
