# Generated by Django 5.1.11 on 2025-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_paid_alter_project_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='url',
            field=models.URLField(blank=True, help_text='Full domain URL including http(s)://', max_length=500, null=True, unique=True),
        ),
    ]
