# Generated by Django 5.1.11 on 2025-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(default='https://makelaw.ke', help_text='Full domain URL including http(s)://', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
