# Generated by Django 5.1.11 on 2025-08-19 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('secret_hash', models.CharField(editable=False, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('domain', 'Domain'), ('project', 'Project')], db_index=True, max_length=10)),
                ('failed_domain_attempts', models.PositiveIntegerField(default=0)),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeySnapshot',
            fields=[
                ('uuid', models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
