# Generated by Django 5.1.11 on 2025-08-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_quota', models.PositiveIntegerField(default=0, help_text='Default quota for this feature')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('P', 'Premium')], default='B', help_text='Plan type: Basic, Standard, or Premium', max_length=1, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in KES', max_digits=10, null=True)),
                ('request_limit', models.PositiveIntegerField(default=100, help_text='Requests allowed per month')),
                ('concurrency_limit', models.PositiveIntegerField(default=1, help_text='Max concurrent requests')),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this is a paid plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requests_per_second', models.PositiveIntegerField(blank=True, help_text='Maximum requests per second for this plan.', null=True)),
                ('requests_per_minute', models.PositiveIntegerField(blank=True, help_text='Maximum requests per minute for this plan.', null=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, help_text='Custom limit for this feature under this plan', null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_plans', to='plans.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['plan__name', 'feature__name'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='plans', through='plans.PlanFeature', to='plans.feature'),
        ),
    ]
