# Generated by Django 5.1.11 on 2025-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.IntegerField()),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('valid_till', models.DateField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.IntegerField()),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('valid_till', models.DateField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pharmtech',
                'verbose_name_plural': 'Pharmtechs',
                'db_table': 'pharmtech',
                'managed': False,
            },
        ),
    ]
