# Generated by Django 5.1.11 on 2025-07-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('memberno', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('standing', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accountant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('profile_image', models.TextField(blank=True)),
                ('advocate_number', models.TextField(blank=True, unique=True)),
                ('postal_address', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('law_firm', models.TextField(blank=True)),
                ('detail_page', models.TextField(blank=True)),
                ('cpd_compliance', models.JSONField(blank=True)),
                ('practice_distribution', models.JSONField(blank=True)),
                ('meta', models.JSONField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'advocates',
                'managed': False,
            },
        ),
    ]
