# Generated by Django 5.1.11 on 2025-08-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_initial'),
        ('projects', '0005_alter_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='projects.domain'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='projects.project'),
        ),
    ]
