# Generated by Django 5.1.11 on 2025-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0003_alter_apikey_domain_alter_apikey_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='access_type',
            field=models.CharField(choices=[('domain', 'Domain'), ('project', 'Project')], db_index=True, default='domain', max_length=10),
            preserve_default=False,
        ),
    ]
