# Generated by Django 5.1.11 on 2025-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0004_apikey_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='failed_domain_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
