# Generated by Django 5.1.11 on 2025-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0005_apikey_blacklisted_apikey_failed_domain_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeySnapshot',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
