# Generated by Django 5.1.11 on 2025-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0006_apikeysnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeysnapshot',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apikeysnapshot',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
