# Generated by Django 5.1.11 on 2025-08-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0007_alter_apikeysnapshot_key_alter_apikeysnapshot_uuid'),
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeysnapshot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_keys_snapshots', to='users.profile'),
        ),
    ]
