# Generated by Django 5.1.11 on 2025-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('ADDRESS', 'Address')], default='Phone', max_length=10, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
