# Generated by Django 5.1.11 on 2025-08-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('ADDRESS', 'Address')], default='Phone', max_length=10, unique=True)),
                ('content', models.TextField()),
                ('label', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://docs.pkenya.makelaw.ke')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
