# Generated by Django 5.1.11 on 2025-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='icon',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='label',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
