# Generated by Django 5.1.11 on 2025-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact_icon_contact_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
