# Generated by Django 5.1.11 on 2025-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_developerdocumentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerdocumentation",
            name="url",
            field=models.URLField(default="https://docs.pkenya.makelaw.ke"),
        ),
    ]
