# Generated by Django 5.1.11 on 2025-07-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
