# Generated by Django 5.1.11 on 2025-07-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Tenant',
        ),
    ]
