# Generated by Django 5.1.11 on 2025-08-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('error_message', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('success_requests', models.PositiveIntegerField(default=0)),
                ('error_requests', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
