# Generated by Django 5.1.11 on 2025-08-13 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('api_keys', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='apiusagesummary',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summary', to='api_keys.apikey'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['timestamp'], name='analytics_a_timesta_5cd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['project', 'timestamp'], name='analytics_a_project_f82073_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['api_key', 'timestamp'], name='analytics_a_api_key_b33850_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiusagesummary',
            unique_together={('api_key', 'date')},
        ),
    ]
