# Generated by Django 5.1.11 on 2025-08-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('projects', '0005_alter_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='projects.project'),
        ),
    ]
